# Generated by Django 5.0.7 on 2024-07-24 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
