# Generated by Django 5.0.7 on 2024-07-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_user_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(default='(71) 99282-9575', max_length=255),
            preserve_default=False,
        ),
    ]
